### ISSUE TITLE
couldn't execute "qemu-img"

### ISSUE THREAD

**Issue by Azithro721** [AntonyZ89/docker-qemu-arm#2]
Device tab s8 plus
Steps : 
1.installed termux
2.installed proto-distro ubuntu latest version 23.10
3.proto-distro login ubuntu
4.apt-get update && apt-get upgrade && apt-get install git && apt-get install expect
5. Git clone repo && cd repo
6. ./termux-setup.sh after removing # infront of export
![SmartSelect_20240207_155106_Termux](https://github.com/AntonyZ89/docker-qemu-arm/assets/116479413/1454adf4-3050-42a1-9bd8-0ca7376d9d2c)

spawn rm -f alpine.img
spawn qemu-img create -f qcow2 alpine.img 4G
couldn't execute "qemu-img": no such file or directory
    while executing
"spawn qemu-img create -f qcow2 alpine.img $env(DISK_SIZE)"
    (file "../installqemu.expect" line 26)

**Comment by AntonyZ89** [comment]
Hey! Are you sure this line is executing as expected? It looks like an error occurred while installing the qemu packages

![image](https://github.com/AntonyZ89/docker-qemu-arm/assets/1340674/c9db6dca-93dd-4723-b535-c3d64aa2235c)

**Comment by AntonyZ89** [comment]
Can you try again using `ubuntu-setup.sh`? A PR has been merged that allows you to configure qemu on ubuntu

`export PREFIX` has been moved to `config.env`, don't forget to uncomment it there

#1

**Comment by Azithro721** [comment]
Worked like charm... Thanku

But u should write in readme to remove sudo from line 5 in ubuntu-setup.sh if using Ubuntu in proot-distro
Cuz Ubuntu in proot-distro doesn't recognise sudo and if tried to install sudo it'll ask for superuser permission i.e., root access

**Comment by Azithro721** [comment]
Also make a telegram group for discussion

**Comment by AntonyZ89** [comment]
> Worked like charm... Thanku
> 
> But u should write in readme to remove sudo from line 5 in ubuntu-setup.sh if using Ubuntu in proot-distro Cuz Ubuntu in proot-distro doesn't recognise sudo and if tried to install sudo it'll ask for superuser permission i.e., root access

Thanks for the feedback, I'll update the ubuntu-setup file. I don't use Ubuntu on proot-distro, so I couldn't test if the file worked correctly

> Also make a telegram group for discussion

I've enabled the discussion tab on repo, I think it will serve for this purpose
